### ISSUE TITLE
cannot run tutorial (stuck on "has user")

### ISSUE THREAD

**Issue by dgreisen** [codingjoe/joeflow#48]
software versions:
Python 3.10.4
Django==4.0.5
joeflow==1.1.1
celery==5.2.7

Thanks for this library. We're investigating whether it is something we can use at our small nonprofit, but we've run into a blocker:

After setting celery up and running it in background, I tried creating a welcome workflow via `127.0.0.1:8000/welcome/start/`. Detail view shows the manual start task successfully completed, but `has user` has a completed of `None`.
![image](https://user-images.githubusercontent.com/505429/176038550-c2544009-9068-4e8d-98e9-38e89859ad7d.png)

When I drop into shell I get:
```
>>> workflow = WelcomeWorkflow.objects.all()[1]
>>> has_user_task = workflow.task_set.all()[1]
>>> has_user_task.status
'scheduled'
```
I was worried it might be a celery issue, so I started with the celery example app (https://github.com/celery/celery/tree/master/examples/django/#running-a-task) made sure I could run the demo tasks, then added the joeflow example to that example app.

Any suggestions where to go from here? Thank you!

---

The following are issues found in the tutorial. Happy to submit a docs PR if that would save you some time.

- detail view missing template resolution order found in other templates
- "and add joeflow to the INSTALLED_APP" is a very important bit lost between the two large grey boxes that draw the eye.
- missing that you need to update the settings to switch to celery backend.
- tutorial missing that you need to install graphviz (https://graphviz.org/download/).
- I would suggest moving dependencies into an unordered list
- would appreciate the filename of each code block to help orientate and provide context. e.g., first two code blocks would be `workflows.py`? I think?
- Would be great to have some troubleshooting tips:
  - if get circular import, then likely forgot to add joeflow to `INSTALLED_APPS`

**Comment by codingjoe** [comment]
Hi @dgreisen,

Thanks for reaching out and your patience with me. First, I greatly enjoy docs improvement PRs. If you have any ideas for improvements, just put them out there.

Now, regarding the Celery issue: What queues is your Celery worker listening too? Your worker needs to listen to `joeflow`. But you can change the queue name to `default` to make your life simpler. Simply override the `JOEFLOW_CELERY_QUEUE_NAME` setting.

I hope that helps. Le me know if you experience any ongoing issues, I'd be delighted to help you out.

Best
Joe

**Comment by caramdache** [comment]
Same issue here, I too am stuck on `has_user`. I'm using `dramatiq` rather than `celery` however.

django==4.0.1
django-dramatiq==0.11.0
dramatiq==1.12.0
joeflow==1.1.1

`rabbitmq-server` is running on a CentOS box.

**Comment by codingjoe** [comment]
Hi @caramdache, have you other tasks, that are already running on dramatiq? I just want to make sure that the problem isn't with the dramatiq setup.

**Comment by caramdache** [comment]
Hi @codingjoe, no, I have no other tasks running on dramatiq. I'm a long time django veteran, but it's my first foray into workflows and `joeflow` seemed to stand out of the crowd.

I could however run the following examples successfully:

- `count_words` from https://dramatiq.io/guide.html
- `hellow_world` from https://www.rabbitmq.com/tutorials/tutorial-one-python.html

I have since noticed that `dramatiq` seems unhappy about `total_retried_messages`, as if the `prometheus` boot process had never been called.

```
2022-08-10 10:16:50,523 CRITICAL Unexpected failure in after_enqueue of <dramatiq.middleware.prometheus.Prometheus object at 0x7f4e49530a30>.
Traceback (most recent call last):
  File ".../python3.9/site-packages/dramatiq/broker.py", line 98, in emit_after
    getattr(middleware, "after_" + signal)(self, *args, **kwargs)
  File ".../python3.9/site-packages/dramatiq/middleware/prometheus.py", line 127, in after_enqueue
    self.total_retried_messages.labels(*labels).inc()
AttributeError: 'Prometheus' object has no attribute 'total_retried_messages'
```
I was expecting django/joeflow/django_dramatiq to do this for me, but apparently not?

**Comment by codingjoe** [comment]
Hi @caramdache,

This seems to be your `django-dramatiq` setup. I suspect this is middleware related. You can check the test app in the repo for some setup hints. Otherwise, I'd encourage you to reach out to `django-dramatiq` for further assistance. I'm no expert in `dramatiq`.

Cheers,
Joe

**Comment by ccurvey** [comment]
For anyone else coming here after searching for that dramatiq issue, this seemed to resolve it for me.  

Add this to your settings file:

```
# dramatiq  -- note that "django_dramatiq" must appear before any custom apps
INSTALLED_APPS.append('django_dramatiq')
INSTALLED_APPS.append('reversion')

# configure your broker appropriately
DRAMATIQ_BROKER = {
    "BROKER": "dramatiq.brokers.redis.RedisBroker",
    "OPTIONS": {
        "url": "redis://127.0.0.1:6379/0",
    },
    "MIDDLEWARE": [
        # comment out the Prometheus middleware (this is a monitoring service, dramatiq is happy without it)
        # "dramatiq.middleware.Prometheus",
        "dramatiq.middleware.AgeLimit",
        "dramatiq.middleware.TimeLimit",
        "dramatiq.middleware.Callbacks",
        "dramatiq.middleware.Retries",
        "django_dramatiq.middleware.DbConnectionsMiddleware",
        "django_dramatiq.middleware.AdminMiddleware",
    ],
}

# now we can install joeflow
INSTALLED_APPS.append("joeflow")
```

Start your dramatiq workers with 

`python manage.py rundramatiq`
