### ISSUE TITLE
Graphs not rendering on ReadTheDocs

### ISSUE THREAD

**Issue by maikhoepfel** [codingjoe/joeflow#56]
![image](https://user-images.githubusercontent.com/509427/195044686-3e0cd926-76e4-4e05-aabb-8a8b45bc3a8a.png)

To me it looks like somebody took care to add graphs, but they're not rendering on [RTD](https://joeflow.readthedocs.io/en/latest/tutorial/workflow.html). I am not sure where else I could browse the docs to have a look at the graph. I really want to see the graph. <3

**Comment by codingjoe** [comment]
Thanks @maikhoepfel. It somehow got lost during the rtfd.io v2 config update, I guess. I'll fix it right away. The graphs are the best part ;)

**Comment by codingjoe** [comment]
They are back in the latest build 🎉

**Comment by maikhoepfel** [comment]
Beautiful, thank you for the prompt fix!
